
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Exceptions - Kotlin - W3cubDocs</title>
  
  <meta name="description" content="This material was written by Aasmund Eldhuset; it is owned by Khan Academy and is licensed for use under CC BY-NC-SA 3.0 US. Please note that this &hellip;">
  <meta name="keywords" content="exceptions, -, kotlin">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/kotlin/docs/tutorials/kotlin-for-py/exceptions/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" integrity="sha256-6/DH7X+2hvUPElJfGsvzm+tgIpmM9zjbYxnpsr6gR1A=" crossorigin="anonymous" href="/assets/application-ebf0c7ed7fb686f50f12525f1acbf39beb6022998cf738db6319e9b2bea04750.css">
  <script type="text/javascript" src="/assets/application-db285287b40ed28fac520fcfd75d7d874692b647b5b5e05968c741dda5de4148.js" integrity="sha256-2yhSh7QO0o+sUg/P1119h0aStke1teBZaMdB3aXeQUg=" crossorigin="anonymous"></script>
  <script src="/json/kotlin.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2572770204602497",
            enable_page_level_ads: true
        });
  </script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/kotlin/" class="_nav-link" title="" style="margin-left:0;">Kotlin</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _kotlin">
				
				
<h1> Exceptions </h1>  <p><em>This material was written by <a href="https://eldhuset.net/" target="_blank">Aasmund Eldhuset</a>; it is owned by <a href="https://www.khanacademy.org/" target="_blank">Khan Academy</a> and is licensed for use under <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/" target="_blank">CC BY-NC-SA 3.0 US</a>. Please note that this is not a part of Khan Academy's official product offering.</em></p> <hr> <h2 id="throwing-and-catching">Throwing and catching</h2> <p>Exceptions pretty much work like they do in Python. You <em>throw</em> (raise) one with <code>throw</code>:</p> <div class="sample" data-highlight-only="" theme="idea"> <pre>throw IllegalArgumentException("Value must be positive")
</pre> </div> <p>You <em>catch</em> it with <code>try</code>/<code>catch</code> (which corresponds to <code>try</code>/<code>except</code> in Python):</p> <div class="sample" data-highlight-only="" theme="idea"> <pre>fun divideOrZero(numerator: Int, denominator: Int): Int {
    try {
        return numerator / denominator
    } catch (e: ArithmeticException) {
        return 0
    }
}
</pre> </div> <p>The <code>catch</code> blocks are tried in order until an exception type is found that matches the thrown exception (it doesn't need to be an exact match; the thrown exception's class can be a subclass of the declared one), and at most one <code>catch</code> block will be executed. If no match is found, the exception bubbles out of the <code>try</code>/<code>catch</code>.</p> <p>The <code>finally</code> block (if any) is executed at the end, no matter what the outcome is: either after the try block completes successfully, or after a catch block is executed (even if another exception is thrown by the catch block), or if no matching catch is found.</p> <p>Unlike Python, <code>try</code>/<code>catch</code> is an expression: the last expression of the <code>try</code> block (if it succeeds) or the chosen <code>catch</code> block becomes the result value (<code>finally</code> doesn't affect the result), so we can refactor the function body above to:</p> <div class="sample" data-highlight-only="" theme="idea"> <pre>return try {
    numerator / denominator
} catch (e: ArithmeticException) {
    0
}
</pre> </div> <p>The base exception class is <code>Throwable</code> (but it is more common to extend its subclass <code>Exception</code>), and there are a ton of built-in exception classes. If you don't find one that match your needs, you can create your own by inheriting from an existing exception class.</p> <p>Note that exceptions are somewhat discouraged in Kotlin except when interacting with Java code. Instead of throwing exceptions in your own code, consider using special return types like <a href="https://arrow-kt.io/docs/datatypes/option/" target="_blank">Option</a> or <a href="https://arrow-kt.io/docs/datatypes/either/" target="_blank">Either</a> from the <a href="https://arrow-kt.io/" target="_blank">Arrow library</a>.</p> <h2 id="nothing">Nothing</h2> <p><code>throw</code> is also an expression, and its return type is the special class <code>Nothing</code>, which does not have any instances. The compiler knows that an expression whose type is <code>Nothing</code> will never return normally, and will therefore generally accept its use even where a different type would normally be required, such as after the <a href="../null-safety/#elvis-operator">Elvis operator</a>. If you make a function that always throws, or that starts an infinite loop, you could declare its return type to be <code>Nothing</code> in order to make the compiler aware of this. One fun example of this is the built-in function <code>TODO</code>, which you can call in any expression (possibly supplying a string argument), and it raises a <code>NotImplementedError</code>.</p> <p>The nullable version <code>Nothing?</code> will be used by the compiler when something is initialized with null and there is no other type information. In <code>val x = null</code>, the type of <code>x</code> will be <code>Nothing?</code>. This type does not have the "never returns normally" semantics; instead, the compiler knows that the value will always be null.</p> <hr> <table> <tbody> <tr> <td><a href="../classes/">← Previous: Classes</a></td> <td><a href="../null-safety/">Next: Null safety →</a></td> </tr> </tbody> </table>
<div class="_attribution">
  <p class="_attribution-p">
    © 2010–2019 JetBrains s.r.o.<br>Licensed under the Apache License, Version 2.0.<br>
    <a href="https://kotlinlang.org/docs/tutorials/kotlin-for-py/exceptions.html" class="_attribution-link" target="_blank">https://kotlinlang.org/docs/tutorials/kotlin-for-py/exceptions.html</a>
  </p>
</div>

				
			</div>
			<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
</amp-auto-ads>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
